codecov:
  require_ci_to_pass: yes

coverage:
  status:
    patch:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto 
        # advanced
        branches: 
          - master
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: 
          - "unit"
        paths: 
          - "src"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
