name:                           Build

on:                             [push]
jobs:
  test:
    name:                       coverage
    runs-on:                    ubuntu-latest
    container:
      image:                    xd009642/tarpaulin:develop
      options:                  --security-opt seccomp=unconfined
    steps:
      - name:                   Checkout repository
        uses:                   actions/checkout@v2

      - name:                   Download nightly
        run: |
          rustup install nightly

      - name:                   Update
        run: |
          apt-get update -y

      - name:                   Install libxcursor
        run: |
          apt-get install -y libxcursor-dev

      - name:                   Install libxrandr
        run: |
          apt-get install -y libxrandr-dev

      - name:                   Install x11-utils
        run: |
          apt-get install -y x11-utils

      - name:                   Install x11-common
        run: |
          apt-get install -y x11-common

      # - name:                   Build
      #   run: |
      #     cargo build

      - name:                   Run test cases
        run: |
          XDG_RUNTIME_DIR=/run/user/1000 RUST_BACKTRACE=1 cargo test --verbose -- --test-threads=1

      # - name:                   Generate code coverage
      #   run: |
      #     RUSTFLAGS=--cfg="tarpaulin_workaround" cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml --avoid-cfg-tarpaulin

      # - name:                   Upload to codecov.io
      #   uses:                   codecov/codecov-action@v1
      #   with:
      #     token:                ${{ secrets.CODECOV_TOKEN }}
      #     fail_ci_if_error:     true
